name: "Development CD: Deploy to Dev Environment"

on:
  push:
    branches:
      - develop

jobs:
  deploy-dev:
    name: "Deploy to Development"
    runs-on: ubuntu-latest
    environment:
      name: development-env
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3

      - name: "Setup GitHub Pages"
        uses: actions/configure-pages@v3

      - name: "Upload Artifact"
        uses: actions/upload-pages-artifact@v2
        with:
          path: "."

      - name: "Deploy to GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@v2
