name: "Development CD: Deploy to Dev Environment"

on:
  push:
    branches:
      - develop

jobs:
  deploy-dev:
    name: "Deploy to Development"
    runs-on: ubuntu-latest
    environment:
      name: development-env
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Setup GitHub Pages"
        uses: actions/configure-pages@v5

      - name: "Upload Artifact"
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./src"

      - name: "Deploy to GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@v4
