name: "Production CD: Deploy to Production"

on:
  push:
    branches:
      - production

jobs:
  deploy-production:
    name: "Deploy to Production"
    runs-on: ubuntu-latest
    environment:
      name: production-env
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Setup GitHub Pages"
        uses: actions/configure-pages@v5

      - name: "Upload Artifact"
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - name: "Deploy to GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@v4
